#!/usr/bin/env bash
#
# setup-daily-brief-cc.sh
# Deploys a SECOND, PARALLEL daily-brief implementation -- same idea as
# setup-daily-brief.sh (pull from the local MCP gateways + web search,
# email the result), but generated by Claude Code CLI authenticated with
# a Pro/Max subscription token instead of a metered Anthropic API key.
# Deliberately kept as an independent project under its own directory,
# config, and cron schedule so the original (proven, currently running)
# daily-brief is never disturbed -- this is for side-by-side comparison,
# not a replacement, until/unless you decide otherwise.
#
# One-time manual prerequisites (secrets, never committed to this repo):
#   1. Node.js + npm on this host (not installed by this script -- it's a
#      real package install, do it yourself):
#        sudo apt install -y nodejs npm
#   2. Claude Code CLI, installed globally via npm:
#        sudo npm install -g @anthropic-ai/claude-code
#   3. A subscription OAuth token: on any machine with a browser and Claude
#      Code CLI installed (e.g. your own workstation), run:
#        claude setup-token
#      This opens a browser to log in, then prints a token to the
#      terminal. It's a one-year token with NO automatic renewal in
#      unattended contexts -- you'll need to repeat this before it expires.
#   4. Create /mnt/data/appdata/daily-brief-cc/config/.env with:
#        CLAUDE_CODE_OAUTH_TOKEN=<token from step 3>
#        EMAIL_TO=<your address>
#   5. Same Microsoft Graph mail setup as the other project, but its OWN
#      independent OAuth grant (separate token cache -- two independent
#      long-running consumers must not share one refresh-token family):
#      after step 4's .env exists, run
#      `venv/bin/python app/graph_login.py` once -- device code flow,
#      prints a URL+code to complete in any browser.
#   Then:
#     ssh mwilkie@<host> mkdir -p /mnt/data/appdata/daily-brief-cc/config
#     scp .env mwilkie@<host>:/mnt/data/appdata/daily-brief-cc/config/
#
# Usage:
#   ./setup-daily-brief-cc.sh

set -euo pipefail

APPDATA_ROOT="/mnt/data/appdata/daily-brief-cc"
APP_DIR="${APPDATA_ROOT}/app"
CONFIG_DIR="${APPDATA_ROOT}/config"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_APP_SRC="${SCRIPT_DIR}/daily-brief-cc"

echo "==> Creating directory structure under ${APPDATA_ROOT}"
mkdir -p "${APP_DIR}" "${CONFIG_DIR}"

if ! command -v claude >/dev/null 2>&1; then
  echo "!! Claude Code CLI not found on this host."
  echo "   See prerequisites 1-2 in this script's header comment, then re-run."
  exit 1
fi

if [ ! -f "${CONFIG_DIR}/.env" ]; then
  echo "!! Missing ${CONFIG_DIR}/.env"
  echo "   Never committed to this repo -- see prerequisites 3-4 in this"
  echo "   script's header comment, create it, then re-run."
  exit 1
fi

echo "==> Copying run.sh + monarch_refresh.sh + parse_claude_result.py + send_mail.py + graph_login.py + mcp.json + prompt.md + requirements.txt into ${APP_DIR}"
cp "${LOCAL_APP_SRC}/run.sh" "${LOCAL_APP_SRC}/monarch_refresh.sh" "${LOCAL_APP_SRC}/parse_claude_result.py" "${LOCAL_APP_SRC}/send_mail.py" "${LOCAL_APP_SRC}/graph_login.py" \
   "${LOCAL_APP_SRC}/mcp.json" "${LOCAL_APP_SRC}/prompt.md" "${LOCAL_APP_SRC}/requirements.txt" "${APP_DIR}/"
chmod +x "${APP_DIR}/run.sh" "${APP_DIR}/monarch_refresh.sh"

echo "==> Creating/updating venv at ${APP_DIR}/venv (for send_mail.py's deps only -- Claude Code CLI needs none of these)"
python3 -m venv "${APP_DIR}/venv"
"${APP_DIR}/venv/bin/pip" install --quiet --upgrade pip
"${APP_DIR}/venv/bin/pip" install --quiet -r "${APP_DIR}/requirements.txt"

echo ""
echo "==> Done."
echo "    Script:  ${APP_DIR}/run.sh"
echo "    Config:  ${CONFIG_DIR}/.env, ${APP_DIR}/prompt.md, ${APP_DIR}/mcp.json"
echo ""
echo "    If you haven't yet, complete the one-time Graph mail login:"
echo "      ${APP_DIR}/venv/bin/python ${APP_DIR}/graph_login.py"
echo ""
echo "    Test it first (prints the brief instead of emailing it):"
echo "      ${APP_DIR}/run.sh --dry-run"
echo ""
echo "    Once that looks right, run it for real once to confirm email delivery:"
echo "      ${APP_DIR}/run.sh"
echo ""
echo "    This is deliberately NOT added to crontab by this script -- it's a"
echo "    side-by-side comparison project. Add a crontab line yourself once"
echo "    you've decided how (or whether) to run it on a schedule, e.g.:"
echo "      30 6 * * * ${APP_DIR}/run.sh >> \$HOME/daily-brief-cc.log 2>&1"
