#!/usr/bin/env bash
#
# setup-mosquitto.sh
# Idempotent deployment script for Mosquitto MQTT broker via Docker Compose.
# Designed for wilkie-home-server (Debian 12, Docker data-root on /mnt/data/docker).
#
# Usage:
#   ./setup-mosquitto.sh            # normal (re)deploy, won't touch existing passwd
#   ./setup-mosquitto.sh --reset    # wipes the MQTT password and creates it fresh
#
# Why the ownership dance matters:
#   The eclipse-mosquitto image's entrypoint ALWAYS drops from root down to its
#   internal "mosquitto" user (uid 1883) before running any command inside the
#   container -- including one-off commands like `mosquitto_passwd`. Passing
#   --user root to `docker run` does NOT prevent this. That means every file
#   and directory Mosquitto (or mosquitto_passwd) needs to write to must
#   already be owned by uid 1883 *before* the container touches it, or you'll
#   get "Unable to open file ... for writing" errors and a restart loop.
#   This script sets that ownership up front so it never has to guess.

set -euo pipefail

# ---- Config you may want to tweak -----------------------------------------
APPDATA_ROOT="/mnt/data/appdata/mosquitto"
COMPOSE_DIR="/mnt/data/appdata/mosquitto"
MQTT_USER="mwilkie"
CONTAINER_NAME="mosquitto"
IMAGE="eclipse-mosquitto:2"
MQTT_PORT="1883"
MQTT_WS_PORT="9001"
MOSQUITTO_UID="1883"
MOSQUITTO_GID="1883"
# -----------------------------------------------------------------------------

RESET=false
if [ "${1:-}" == "--reset" ]; then
  RESET=true
fi

echo "==> Creating directory structure under ${APPDATA_ROOT}"
sudo mkdir -p "${APPDATA_ROOT}/config" "${APPDATA_ROOT}/data" "${APPDATA_ROOT}/log"

# ---- mosquitto.conf ---------------------------------------------------------
CONF_FILE="${APPDATA_ROOT}/config/mosquitto.conf"
if [ -f "${CONF_FILE}" ]; then
  echo "==> ${CONF_FILE} already exists, leaving it alone"
else
  echo "==> Writing ${CONF_FILE}"
  sudo tee "${CONF_FILE}" > /dev/null <<EOF
# Mosquitto config — generated by setup-mosquitto.sh

persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Require authentication — no anonymous clients
allow_anonymous false
password_file /mosquitto/config/passwd

# Standard MQTT
listener ${MQTT_PORT}

# MQTT over WebSockets (handy for browser-based dashboards / debugging tools)
listener ${MQTT_WS_PORT}
protocol websockets
EOF
fi

# ---- Ownership FIRST, before any container ever touches these paths -------
# This is the key fix: uid 1883 needs write access to config/, data/, and log/
# before mosquitto (or mosquitto_passwd) ever runs against them.
echo "==> Setting ownership to uid:gid ${MOSQUITTO_UID}:${MOSQUITTO_GID} (mosquitto container user)"
sudo chown -R "${MOSQUITTO_UID}:${MOSQUITTO_GID}" "${APPDATA_ROOT}"

# ---- Password file ------------------------------------------------------
PASSWD_FILE="${APPDATA_ROOT}/config/passwd"

if [ "${RESET}" == true ] && [ -f "${PASSWD_FILE}" ]; then
  echo "==> --reset passed, removing existing password file"
  sudo rm -f "${PASSWD_FILE}"
fi

if [ -f "${PASSWD_FILE}" ]; then
  echo "==> Password file already exists, leaving it alone"
  echo "    (re-run this script with --reset if you want to set a new password)"
else
  echo "==> No password file found — creating MQTT user '${MQTT_USER}'"
  echo "    You will be prompted to set a password for this user."
  # No --user override needed: the entrypoint drops to uid 1883 on its own,
  # and since the config/ directory is already owned by 1883, it can write
  # the new file without any permission errors.
  docker run --rm -it \
    -v "${APPDATA_ROOT}/config:/mosquitto/config" \
    "${IMAGE}" \
    mosquitto_passwd -c /mosquitto/config/passwd "${MQTT_USER}"

  # Belt-and-suspenders: make sure the file that just got created is still
  # owned correctly (it should be already, but this costs nothing).
  sudo chown "${MOSQUITTO_UID}:${MOSQUITTO_GID}" "${PASSWD_FILE}"
  sudo chmod 600 "${PASSWD_FILE}"
fi

# ---- docker-compose.yml ------------------------------------------------
COMPOSE_FILE="${COMPOSE_DIR}/docker-compose.yml"
echo "==> Writing ${COMPOSE_FILE}"
sudo tee "${COMPOSE_FILE}" > /dev/null <<EOF
services:
  mosquitto:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${MQTT_PORT}:${MQTT_PORT}"
      - "${MQTT_WS_PORT}:${MQTT_WS_PORT}"
    volumes:
      - ${APPDATA_ROOT}/config:/mosquitto/config
      - ${APPDATA_ROOT}/data:/mosquitto/data
      - ${APPDATA_ROOT}/log:/mosquitto/log
EOF

# ---- Bring it up ---------------------------------------------------------
echo "==> Starting Mosquitto via docker compose"
cd "${COMPOSE_DIR}"
docker compose up -d --force-recreate

echo "==> Waiting a few seconds for the broker to settle..."
sleep 4

echo ""
echo "==> Container status:"
docker ps --filter "name=${CONTAINER_NAME}"

echo ""
echo "==> Recent logs:"
docker logs "${CONTAINER_NAME}" --tail 15

echo ""
echo "==> Done."
echo "    Broker running on port ${MQTT_PORT} (MQTT) and ${MQTT_WS_PORT} (WebSockets)"
echo "    Config:   ${CONF_FILE}"
echo "    Password: ${PASSWD_FILE}  (user: ${MQTT_USER})"
echo ""
echo "    Test with (two terminals):"
echo "      docker exec -it ${CONTAINER_NAME} mosquitto_sub -h localhost -u ${MQTT_USER} -P <password> -t test/topic"
echo "      docker exec -it ${CONTAINER_NAME} mosquitto_pub -h localhost -u ${MQTT_USER} -P <password> -t test/topic -m 'hello'"
