#!/usr/bin/env bash
#
# setup-zigbee2mqtt.sh
# Idempotent deployment script for Zigbee2MQTT via Docker Compose, using the
# SONOFF Zigbee 3.0 USB Dongle Plus (V2, EFR32MG21-based).
# Designed for wilkie-home-server (Debian 12, Docker data-root on /mnt/data/docker).
#
# PREREQUISITE: Mosquitto must already be running (see setup-mosquitto.sh) —
# Zigbee2MQTT connects to it over localhost:1883 using the MQTT user created
# there. You'll be prompted for that user's password on first run.
#
# Usage:
#   ./setup-zigbee2mqtt.sh
#
# Re-running this script is safe: it will recreate the zigbee2mqtt container
# with current settings, but does not touch your existing configuration.yaml
# or paired-device network data (persisted under APPDATA_ROOT/data).

set -euo pipefail

# ---- Config you may want to tweak -----------------------------------------
APPDATA_ROOT="/mnt/data/appdata/zigbee2mqtt"
COMPOSE_DIR="/mnt/data/appdata/zigbee2mqtt"
CONTAINER_NAME="zigbee2mqtt"
IMAGE="ghcr.io/koenkk/zigbee2mqtt:latest"
MQTT_USER="mwilkie"
MQTT_SERVER="mqtt://localhost:1883"
FRONTEND_PORT="8099"   # 8080 is already used by OTBR's web-forward service
SERIAL_BY_ID_GLOB="/dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_*"
# -----------------------------------------------------------------------------

echo "==> Looking for the SONOFF Zigbee 3.0 dongle under /dev/serial/by-id/"
SERIAL_DEVICE=$(ls ${SERIAL_BY_ID_GLOB} 2>/dev/null | head -n1 || true)

if [ -z "${SERIAL_DEVICE}" ]; then
  echo "!! Could not find a device matching ${SERIAL_BY_ID_GLOB}"
  echo "   Is the dongle plugged in? Check with: ls /dev/serial/by-id/"
  exit 1
fi
echo "==> Found dongle at: ${SERIAL_DEVICE}"

echo "==> Creating directory structure under ${APPDATA_ROOT}"
mkdir -p "${APPDATA_ROOT}/data"

# ---- configuration.yaml ----------------------------------------------------
CONFIG_FILE="${APPDATA_ROOT}/data/configuration.yaml"
if [ -f "${CONFIG_FILE}" ]; then
  echo "==> ${CONFIG_FILE} already exists, leaving it alone"
else
  echo "==> No configuration.yaml found — creating one"
  echo "    Enter the MQTT password for user '${MQTT_USER}' (set in setup-mosquitto.sh):"
  read -r -s -p "    MQTT password: " MQTT_PASSWORD
  echo ""

  tee "${CONFIG_FILE}" > /dev/null <<EOF
# Zigbee2MQTT config — generated by setup-zigbee2mqtt.sh
homeassistant: true
permit_join: false

mqtt:
  base_topic: zigbee2mqtt
  server: ${MQTT_SERVER}
  user: ${MQTT_USER}
  password: "${MQTT_PASSWORD}"

serial:
  port: /dev/ttyACM0
  adapter: ember

frontend:
  port: ${FRONTEND_PORT}

advanced:
  network_key: GENERATE
  log_level: info
EOF
  unset MQTT_PASSWORD
fi

# ---- docker-compose.yml ------------------------------------------------
COMPOSE_FILE="${COMPOSE_DIR}/docker-compose.yml"
echo "==> Writing ${COMPOSE_FILE}"
tee "${COMPOSE_FILE}" > /dev/null <<EOF
services:
  zigbee2mqtt:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${APPDATA_ROOT}/data:/app/data
      - /run/udev:/run/udev:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - ${SERIAL_DEVICE}:/dev/ttyACM0
EOF

# ---- Bring it up ---------------------------------------------------------
echo "==> Starting Zigbee2MQTT via docker compose"
cd "${COMPOSE_DIR}"
docker compose up -d --force-recreate

echo "==> Waiting a few seconds for Zigbee2MQTT to settle..."
sleep 6

echo ""
echo "==> Container status:"
docker ps --filter "name=${CONTAINER_NAME}"

echo ""
echo "==> Recent logs:"
docker logs "${CONTAINER_NAME}" --tail 30

echo ""
echo "==> Done."
echo "    Container:    ${CONTAINER_NAME}"
echo "    Serial device: ${SERIAL_DEVICE}"
echo "    Config:       ${CONFIG_FILE}"
echo ""
echo "    Web UI: http://$(hostname -I | awk '{print $1}'):${FRONTEND_PORT}"
echo ""
echo "    Notes:"
echo "    - permit_join is false by default. To pair new devices, either flip"
echo "      it to true in ${CONFIG_FILE} and restart, or use the 'Permit join'"
echo "      toggle in the web UI (safer, since it can auto re-disable on a timer)."
echo "    - Home Assistant MQTT discovery is enabled (homeassistant: true), so"
echo "      paired devices should show up automatically in HA once bridged."
echo ""
echo "    Check status any time with:"
echo "      docker ps --filter name=${CONTAINER_NAME}"
echo "      docker logs ${CONTAINER_NAME} --tail 30"
