#!/usr/bin/env bash
#
# setup-daily-brief-oai.sh
# Deploys a THIRD daily-brief implementation alongside daily-brief-cc: same
# prompt.md and send_mail.py (copied from daily-brief-cc/, so there's one
# source of truth for each), but generated by Azure OpenAI (gpt-6.1-sol on
# mark-9211-resource) instead of Claude Code CLI. Why: daily-brief-cc draws
# down the Claude subscription's usage limits every morning; Azure OpenAI is
# first-party Azure, so it's paid from the Visual Studio subscription's
# monthly credit (which has a spending limit on -- it can never bill a card).
#
# The claude.ai connectors daily-brief-cc relies on don't exist outside
# Claude, so brief.py replaces them: Google Calendar via secret iCal URLs
# (config/calendars.json), Outlook via this project's own Graph grant with
# Mail.Read added.
#
# One-time manual prerequisites (secrets, never committed to this repo):
#   1. /mnt/data/appdata/daily-brief-oai/config/.env with:
#        AZURE_OPENAI_BASE_URL=https://mark-9211-resource.openai.azure.com/openai/v1/
#        AZURE_OPENAI_API_KEY=<az cognitiveservices account keys list -n mark-9211-resource -g rg-mark-9211>
#        AZURE_OPENAI_DEPLOYMENT=gpt-6.1-sol
#        EMAIL_TO=<your address>
#   2. /mnt/data/appdata/daily-brief-oai/config/calendars.json: each
#      calendar's "Secret address in iCal format" (Google Calendar ->
#      Settings -> the calendar -> Integrate calendar). Shape:
#      daily-brief-oai/calendars.example.json. chmod 600 -- the URLs are
#      read access to the calendar.
#   3. After this script has run once: `app/venv/bin/python app/graph_login.py`
#      (device code flow, Mail.Send + Mail.Read).
#
# Usage:
#   ./setup-daily-brief-oai.sh

set -euo pipefail

APPDATA_ROOT="/mnt/data/appdata/daily-brief-oai"
APP_DIR="${APPDATA_ROOT}/app"
CONFIG_DIR="${APPDATA_ROOT}/config"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_APP_SRC="${SCRIPT_DIR}/daily-brief-oai"
SHARED_SRC="${SCRIPT_DIR}/daily-brief-cc"

echo "==> Creating directory structure under ${APPDATA_ROOT}"
mkdir -p "${APP_DIR}" "${CONFIG_DIR}"
chmod 700 "${CONFIG_DIR}"

if [ ! -f "${CONFIG_DIR}/.env" ]; then
  echo "!! Missing ${CONFIG_DIR}/.env -- see prerequisite 1 in this script's header comment."
  exit 1
fi

echo "==> Copying brief.py + graph_login.py + run.sh + requirements.txt, plus shared prompt.md + send_mail.py from daily-brief-cc"
cp "${LOCAL_APP_SRC}/brief.py" "${LOCAL_APP_SRC}/graph_login.py" "${LOCAL_APP_SRC}/run.sh" \
   "${LOCAL_APP_SRC}/monarch_refresh.py" "${LOCAL_APP_SRC}/requirements.txt" "${APP_DIR}/"
cp "${SHARED_SRC}/prompt.md" "${SHARED_SRC}/send_mail.py" "${APP_DIR}/"
chmod +x "${APP_DIR}/run.sh"

echo "==> Creating/updating venv at ${APP_DIR}/venv"
python3 -m venv "${APP_DIR}/venv"
"${APP_DIR}/venv/bin/pip" install --quiet --upgrade pip
"${APP_DIR}/venv/bin/pip" install --quiet -r "${APP_DIR}/requirements.txt"

echo ""
echo "==> Done."
[ -f "${CONFIG_DIR}/calendars.json" ] || echo "    !! ${CONFIG_DIR}/calendars.json missing -- Calendar section will report unavailable (prerequisite 2)."
[ -f "${CONFIG_DIR}/graph_token_cache.json" ] || echo "    !! Run once: ${APP_DIR}/venv/bin/python ${APP_DIR}/graph_login.py"
echo "    Test: ${APP_DIR}/run.sh --dry-run"
echo "    Cron:"
echo "      0 6 * * * ${APP_DIR}/venv/bin/python ${APP_DIR}/monarch_refresh.py >> \$HOME/daily-brief-oai.log 2>&1"
echo "      30 6 * * * ${APP_DIR}/run.sh >> \$HOME/daily-brief-oai.log 2>&1"
