#############################################################################
#
# Makefile for librf24mesh examples on Raspberry Pi
#
# By:  TMRh20
# Date:    2013/09
#
# Description:
# ------------
# use make all and make install to install the examples
# You can change the install directory by editing the prefix line
#
prefix := /usr/local

# The recommended compiler flags for the Raspberry Pi
CCFLAGS=-fpermissive -Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s -g

Test: HomeAutomationWebAPI.o WebAPI.o Test.cpp
	g++ ${CCFLAGS} -Wall -lcrypto -I../ -lrf24-bcm -L/usr/lib/arm-linux-gnueabihf -lcurl HomeAutomationWebAPI.o WebAPI.o Test.cpp -o Test

HomeAutomationWebApi: HomeAutomationWebApi.cpp WebAPI.o
	g++ HomeAutomationWebAPI.cpp -c 

WebAPI: WebAPI.cpp
	g++ WebAPI.cpp -c 

